import "@/styles/globals.css";

import { Inter } from "next/font/google";
import RootProvider from "@/app/providers";
import NavigationBar from "@/components/layout/navigation-bar";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <RootProvider>
      <html lang="en">
        <body className={`bg-gray-100 font-sans ${inter.variable}`}>
          <NavigationBar />
          {children}
          <Toaster />
        </body>
      </html>
    </RootProvider>
  );
}
